name: Generator
authors: [MartinErSej]
version: '${project.version}'
main: dk.martinersej.generator.Generator
depend:
  - PlotSquared
  - Vault
softdepend:
  - PlaceholderAPI
commands:
  generator:
  genlist:
database: true