name: Generator
authors: [ MartinErSej ]
version: '${project.version}'
main: dk.martinersej.generator.Generator
database: true
depend:
  - PlotSquared
  - Vault
softdepend:
  - PlaceholderAPI
commands:
  generator:
    description: Generator command
    usage: /<command>
    permission: generator.command
  genlist:
    description: Generator list command
    usage: /<command>
  discord:
    description: Discord command
    usage: /<command>
  team:
    description: Team command
    usage: /<command>
  shop:
    description: Shop command
    usage: /<command>